MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=homework
MYSQL_USER=user
MYSQL_PASSWORD=user
MYSQL_PORT=3306

set JWT_SECRET=ASDFAFDSASDJKFASDFJSALDKFJSDSDFSAFD

set DB_HOST=192.168.1.109
set DB_PORT=3306
set DB_USER=user
set DB_PASSWORD=user
set DB_NAME=homework
