FROM golang:1.22-alpine AS builder
WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata
COPY HomeworkSystem/go.mod HomeworkSystem/go.sum ./HomeworkSystem/
WORKDIR /app/HomeworkSystem
RUN go mod download

COPY HomeworkSystem/ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /homework ./cmd/main.go

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata && \
  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  echo "Asia/Shanghai" > /etc/timezone

WORKDIR /app
COPY --from=builder /homework /app/homework
EXPOSE 8080
ENTRYPOINT ["/app/homework"]
