# 第一阶段：构建阶段
FROM node:24.13 AS builder
ARG GITURL=https://github.com/xieyuxuan109/HomeworkWeb.git
WORKDIR /
RUN git clone $GITURL \
    && cd /HomeworkWeb/frontend-03 \
    && npm install \
    && npm run build

# 第二阶段：运行阶段（极简镜像）
FROM nginx
RUN  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo "Asia/Shanghai" > /etc/timezone
WORKDIR /
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /HomeworkWeb/frontend-03/dist /usr/share/nginx/html
EXPOSE 80
